- name: Deploy HABP
  hosts: "{{host}}"
  user: root
  roles:
  - critical
  - payload
  - monitor
  - sstv
  - gpsd
  - role: ntpd
    from_gps: true
  tasks:
  - name: Update all packages
    yum: name=* state=latest
